overlay: 1.0.0
info:
  title: API Evangelist enhancements for VTS Lease API
  version: 1.0.0
extends: openapi/vts-openapi.yml
actions:
- target: $.info
  update:
    x-apievangelist-enriched: true
    x-apievangelist-rating-round: '2026-07-21'
    x-apievangelist-source: harvested from readme.vts.com per-operation OpenAPI fragments
